# Generated by Django 3.2 on 2021-04-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0002_alter_courses_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
